/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

//TODO check if this is fine or if you need another replicant

export interface CurrentMatch {
  id: string;
  stage: string;
  startTime: number;
  type: 'bo1' | 'bo3' | 'bo5' | 'showmatch' | 'quiz';
  players: {
    player1: {
      name: string;
      srcUsername?: string;
      manualPb?: boolean;
      avatar: string;
      showAvatar: boolean;
    };
    player2: {
      name: string;
      srcUsername?: string;
      manualPb?: boolean;
      avatar: string;
      showAvatar: boolean;
    };
    player3?: {
      name: string;
      srcUsername?: string;
      manualPb?: boolean;
      avatar: string;
      showAvatar: boolean;
    };
    player4?: {
      name: string;
      srcUsername?: string;
      manualPb?: boolean;
      avatar: string;
      showAvatar: boolean;
    };
  };
  segments: {
    name:
      | 'Trevor%'
      | 'Countryside'
      | 'Blitz Play'
      | 'Deep Inside'
      | 'Fresh Meat'
      | 'The Third Way'
      | 'All Stunt Jumps'
      | 'All Races'
      | 'Epsilon Program';
    pickedBy: string;
    wonBy: string | null;
  }[];
}
