/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentSegment {
	name:
		| 'Trevor%'
		| 'Countryside'
		| 'Blitz Play'
		| 'Deep Inside'
		| 'Fresh Meat'
		| 'The Third Way'
		| 'All Stunt Jumps'
		| 'All Races'
		| 'Epsilon Program';
	pickedBy: string;
}
