/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type questions = {
    id: string;
    question: string;
    type: 'normal' | 'enumeration' | 'estimate';
    answers: {
      answer1: string,
      answer2: string,
      answer3: string,
      answer4: string,
    };
  }[];