/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Player2 {
	name: string;
	src: string;
	pb?: string;
	hasAvatar?: boolean;
	avatar?: string;
	finishTime?: string;
	[k: string]: unknown;
}
